project_id = "rwgktdylzedlfroqlhfl"

[functions.paystack-init]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.hero-webhook-sms]
verify_jwt = false

[functions.refund-check]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
