// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwgktdylzedlfroqlhfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3Z2t0ZHlsemVkbGZyb3FsaGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MzExNzcsImV4cCI6MjA4NTAwNzE3N30.5cWXBAolF0l1-JOn59YT3PUJmzagg6fqlWjgqLlWDqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});